### ISSUE TITLE
Extension does not work with `search_project_path` set to `true`.

### ISSUE THREAD

**Issue by siddhpant** [poucotm/SublimeLinter-contrib-verilator#10]
Here's the error on console:

```
SublimeLinter: ERROR: Unhandled exception:
Traceback (most recent call last):
  File "/home/yoojer/.config/sublime-text/Installed Packages/SublimeLinter.sublime-package/lint/backend.py", line 157, in execute_lint_task
    errors = linter.lint(code, view_has_changed)
  File "/home/yoojer/.config/sublime-text/Installed Packages/SublimeLinter-contrib-verilator.sublime-package/linter.py", line 86, in lint
    return super(Verilator, self).lint(code, view_has_changed)
  File "/home/yoojer/.config/sublime-text/Installed Packages/SublimeLinter.sublime-package/lint/linter.py", line 1163, in lint
    output = self.run(cmd, code)
  File "/home/yoojer/.config/sublime-text/Installed Packages/SublimeLinter.sublime-package/lint/linter.py", line 1568, in run
    return self.tmpfile(cmd, code)
  File "/home/yoojer/.config/sublime-text/Installed Packages/SublimeLinter-contrib-verilator.sublime-package/linter.py", line 165, in tmpfile
    for path in prjsrc:
TypeError: 'NoneType' object is not iterable
```

**Comment by siddhpant** [comment]
nvm, `sources` need to be set in `.sublime-settings`.
